In [96]:
import numpy as np

In [97]:
RATINGS_MAT = np.array([[3, 0, 1, 5, 3],
                        [1, 5, 5, 1, 1],
                        [0, 4, 3, 0, 1],
                        [0, 1, 2, 0, 5],
                        [1, 1, 1, 0, 1]])

'''
The question here is what happens to the first column when we try
the matrix completion reccomendation algorithm

Does it take large influence from the last two columns
'''

RATINGS_MAT

array([[3, 0, 1, 5, 3],
       [1, 5, 5, 1, 1],
       [0, 4, 3, 0, 1],
       [0, 1, 2, 0, 5],
       [1, 1, 1, 0, 1]])

In [98]:
U, S, V = np.linalg.svd(RATINGS_MAT)

largest_s = S[0]
second_largest_s = S[1]
third_largest_s = S[3]

print(f'The largest singular value is {largest_s} and the second largest singular value {second_largest_s}')

S

The largest singular value is 10.051400364084126 and the second largest singular value 6.2446115269259765


array([10.05140036,  6.24461153,  3.99451421,  0.83243215,  0.57016709])

In [99]:
# New ratings 

NEW_SIGMA = np.diag(np.array([largest_s, second_largest_s, third_largest_s]))

REC = U[:, :3] @ NEW_SIGMA  @ V[:, :3].T

REC

array([[-2.07344891, -3.74584966,  0.35758834, -3.81693896,  2.99275681],
       [ 2.79304475, -1.23462425,  2.71113449, -5.48909939, -2.15173905],
       [ 2.19069823, -0.52539389,  1.93900088, -3.58854579, -2.00535656],
       [-0.40373007, -2.19914111,  1.08148315, -3.4626033 , -0.27525095],
       [ 0.29397469, -0.67952081,  0.59988121, -1.53872759, -0.23431388]])

In [100]:
# Lets compare:
REC_STR = np.array_str(REC, precision=4, suppress_small=True)
RATINGS_STR = np.array_str(RATINGS_MAT, precision=4, suppress_small=True)

In [101]:
print(REC_STR)
print(RATINGS_STR)

[[-2.0734 -3.7458  0.3576 -3.8169  2.9928]
 [ 2.793  -1.2346  2.7111 -5.4891 -2.1517]
 [ 2.1907 -0.5254  1.939  -3.5885 -2.0054]
 [-0.4037 -2.1991  1.0815 -3.4626 -0.2753]
 [ 0.294  -0.6795  0.5999 -1.5387 -0.2343]]
[[3 0 1 5 3]
 [1 5 5 1 1]
 [0 4 3 0 1]
 [0 1 2 0 5]
 [1 1 1 0 1]]
